# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - go tool goreleaser release --snapshot --clean
    silent: false
  wire:
    cmds:
      - cd internal/infra/di && wire
