// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"goddd/internal/application"
	"goddd/internal/infra/database"
	"goddd/internal/infra/logger"
	"goddd/internal/infra/repository"
	"goddd/internal/ports/http"
	"goddd/internal/ports/http/v0/handler"
	"goddd/pkg/config"
)

// Injectors from wire.go:

func InitializeApp() *http.App {
	appConfig := config.ProvideConfig()
	slogLogger := logger.NewLogger(appConfig)
	db := database.NewDB(appConfig)
	bookRepository := repository.NewBookRepository(db)
	bookService := application.NewBookService(bookRepository)
	bookHandler := handler.NewBookHandler(bookService, slogLogger)
	v := http.ProvideV0Routers(bookHandler)
	app := http.NewApp(slogLogger, appConfig, v...)
	return app
}
